/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;

import com.google.common.primitives.Longs;

import org.rocksdb.Options;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        RocksDB.loadLibrary();
        try (final Options options = new Options().setCreateIfMissing(true)) {
            try (final RocksDB db = RocksDB.open(options, "/home/jtamayo/src/dbs/test1")) {
                // do something

                var key = "hello".getBytes();
                final byte[] value = db.get(key);
                if (value == null) { // value == null if key1 does not exist in db.
                    System.out.println("Storing zero");
                    db.put(key, Longs.toByteArray(0));
                } else {
                    var next = Longs.fromByteArray(value) + 1;
                    System.out.println("Incrementing to " + next);
                    db.put(key, Longs.toByteArray(next));
                }
            }
        } catch (RocksDBException e) {
            // do some error handling
            throw new RuntimeException(e);
        }
    }
}
